format_version: 3

pipelines:
  myawesome-service-1-build-dev:
    group: TEAMNAME
    materials:
      mygit:
        git: https://github.com/praks-1529/myawesome.git
        branch: develop
    environment_variables:
      DOCKER_REGISTRY: 479580041174.dkr.ecr.ap-south-1.amazonaws.com
      IMAGE_NAME: myawesome-service-1
    stages:
    - build:
        clean_workspace: true
        jobs:
          build:
            elastic_profile_id: myawesome-java-8
            artifacts:
            - build:
                source: image_ref
            tasks:
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn clean package"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn clean package -Dspring.profiles.active=docker"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec > version.txt"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "echo ${DOCKER_REGISTRY}/${IMAGE_NAME}:v`git rev-list HEAD --count`.0 > image_ref"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "eval $(aws ecr get-login --no-include-email --region ap-south-1) && docker build --build-arg version=`cat version.txt` -t `cat image_ref` ."
            - exec:
                command: bash
                arguments:
                - "-c"      
                - "eval $(aws ecr get-login --no-include-email --region us-east-1) && docker push `cat image_ref`"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "cat image_ref"

  myawesome-service-1-build-qa:
    group: TEAMNAME
    materials:
      mygit:
        git: https://github.com/praks-1529/myawesome.git
        branch: verify
    environment_variables:
      DOCKER_REGISTRY: 479580041174.dkr.ecr.ap-south-1.amazonaws.com
      IMAGE_NAME: myawesome-service-1
    stages:
    - build:
        clean_workspace: true
        jobs:
          build:
            elastic_profile_id: myawesome-java-8
            artifacts:
            - build:
                source: image_ref
            tasks:
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn clean package"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn clean package -Dspring.profiles.active=docker"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec > version.txt"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "echo ${DOCKER_REGISTRY}/${IMAGE_NAME}-qa:v`git rev-list HEAD --count`.0 > image_ref"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "eval $(aws ecr get-login --no-include-email --region ap-south-1) && docker build --build-arg version=`cat version.txt` -t `cat image_ref` ."
            - exec:
                command: bash
                arguments:
                - "-c"      
                - "eval $(aws ecr get-login --no-include-email --region us-east-1) && docker push `cat image_ref`"
            - exec:
                command: bash
                arguments:
                - "-c"
                - "cat image_ref"

  myawesome-service-1-in-dev-aps1:
    group: TEAMNAME
    parameters:
      aws_profile: dev
      region_short: aps1
      region: ap-south-1
      component_name: myawesome-service-1
      env: dev
      product_market: in
      upstream_build_pipeline: "myawesome-service-1-build-dev"
      team_name: "myawesome-team-name"
    materials:
      upstream:
        pipeline: myawesome-service-1-build-dev
        stage: build
      mygit:
        git: https://github.com/praks-1529/myawesome.git
        branch: develop

    stages:
      - terraform-plan: &terraform-plan
          clean_workspace: true
          jobs:
              deploy:
                elastic_profile_id: "terraform-#{env}"
                artifacts:
                - build:
                    source: terraform/tf_plan_output.txt
                environment_variables:
                  AWS_PROFILE: "#{aws_profile}"
                  REGION: "#{region}"
                  COMPONENT_NAME: "#{component_name}"
                  ENV: "#{env}"
                  PRODUCT_MARKET: "#{product_market}"
                  TF_EXE: "terraform"
                  TEAM_NAME: "#{team_name}"
                tasks:
                  - exec:
                      command: bash
                      working_directory: terraform
                      arguments:
                        - "-c"
                        - "AWS_PROFILE=#{aws_profile} ./tf_plan.sh > tf_plan_output.txt"

      - terraform-apply: &terraform-apply
          clean_workspace: true
          jobs:
              deploy:
                elastic_profile_id: "terraform-#{env}"
                artifacts:
                - build:
                    source: terraform/env.sh
                environment_variables:
                  AWS_PROFILE: "#{aws_profile}"
                  REGION: "#{region}"
                  COMPONENT_NAME: "#{component_name}"
                  ENV: "#{env}"
                  PRODUCT_MARKET: "#{product_market}"
                  TF_EXE: "terraform"
                  TEAM_NAME: "#{team_name}"
                tasks:
                  - exec:
                      command: bash
                      working_directory: terraform
                      arguments:
                        - "-c"
                        - "AWS_PROFILE=#{aws_profile} ./tf_apply.sh"
                  - exec:
                      command: bash
                      working_directory: terraform
                      arguments:
                        - "-c"
                        - "./tf_gen_env.sh > env.sh"

      - kube-deploy: &kube-deploy
          clean_workspace: true
          jobs:
              deploy:
                elastic_profile_id: "kube-#{env}"
                artifacts:
                - build:
                    source: k8s/deployment-manifest.json
                - build:
                    source: k8s/namespace-manifest.json
                - build:
                    source: k8s/service-manifest.json
                environment_variables:
                  AWS_PROFILE: "#{aws_profile}"
                  REGION: "#{region}"
                  COMPONENT_NAME: "#{component_name}"
                  ENV: "#{env}"
                  PRODUCT_MARKET: "#{product_market}"
                  TEAM_NAME: "#{team_name}"
                tasks:
                  - fetch:
                      pipeline: "#{upstream_build_pipeline}"
                      stage: build
                      job: build
                      is_file: yes
                      source: image_ref
                  - fetch:
                      pipeline: "#{component_name}-#{product_market}-#{env}-#{region_short}"
                      stage: terraform-apply
                      job: deploy
                      is_file: yes
                      source: env.sh
                  - exec:
                      command: bash
                      arguments:
                        - "-c"
                        - "cat image_ref"
                  - exec:
                      command: bash
                      working_directory: k8s
                      arguments:
                        - "-c"
                        - "export AWS_PROFILE=#{aws_profile} && \
                           export REGION=#{region} && \
                           export COMPONENT_NAME=#{component_name} && \
                           export PRODUCT_MARKET=#{product_market} && \
                           export IMAGE=`cat ../image_ref` && \
                           export ENV=#{env} && \
                           export REPLICA=2 && \
                           export TEAM_NAME=#{team_name} && \
                           source ../env.sh && \
                           ./deploy_kube namespace-manifest.jsonnet namespace-manifest.json --deploy"
                  - exec:
                      command: bash
                      working_directory: k8s
                      arguments:
                        - "-c"
                        - "export AWS_PROFILE=#{aws_profile} && \
                           export REGION=#{region} && \
                           export COMPONENT_NAME=#{component_name} && \
                           export PRODUCT_MARKET=#{product_market} && \
                           export IMAGE=`cat ../image_ref` && \
                           export ENV=#{env} && \
                           export REPLICA=2 && \
                           export TEAM_NAME=#{team_name} && \
                           source ../env.sh && \
                           ./deploy_kube deployment-manifest.jsonnet deployment-manifest.json --deploy"
                  - exec:
                      command: bash
                      working_directory: k8s
                      arguments:
                        - "-c"
                        - "export AWS_PROFILE=#{aws_profile} && \
                           export REGION=#{region} && \
                           export COMPONENT_NAME=#{component_name} && \
                           export PRODUCT_MARKET=#{product_market} && \
                           export IMAGE=`cat ../image_ref` && \
                           export ENV=#{env} && \
                           export REPLICA=2 && \
                           export TEAM_NAME=#{team_name} && \
                           source ../env.sh && \
                           ./deploy_kube service-manifest.jsonnet service-manifest.json --deploy"

  myawesome-service-1-in-qa-aps1:
    group: TEAMNAME
    parameters:
      aws_profile: qa
      region_short: aps1
      region: ap-south-1
      component_name: myawesome-service-1
      manifest_file: deployment-manifest.json
      env: qa
      product_market: in
      upstream_build_pipeline: "myawesome-service-1-build-qa"
      team_name: "myawesome-team-name"
    materials:
      upstream:
        pipeline: myawesome-service-1-build-qa
        stage: build
      mygit:
        git: https://github.com/praks-1529/myawesome.git
        branch: verify
    stages:
      # - terraform-plan: *terraform-plan
      - terraform-apply: *terraform-apply