apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
  - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
    image: 479580041174.dkr.ecr.ap-south-1.amazonaws.com/myawesome-gocd-agent-java-8:1.0
    securityContext:
      privileged: true
  imagePullSecrets:
  - name: regcred.qa
